services:
  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    ports:
      - "8080:8080"

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    ports:
      - "8081:8081"
