apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.name }}-es
spec:
  refreshInterval: {{ .Values.refreshInterval }}
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: {{ .Values.name }}-secret
  data:
    {{- range .Values.secretKeys }}
    - secretKey: {{ . }}
      remoteRef:
        key: {{ $.Values.awsSecretPath }}
        property: {{ . }}
    {{- end }}