apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: order-service-es
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: order-service-secret
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: prod/order-service
        property: DATABASE_URL
    - secretKey: API_KEY
      remoteRef:
        key: prod/order-service
        property: API_KEY
